FROM python:3.5-alpine
LABEL maintainer="raymond.xu@sap.com"
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY . /usr/src/app
RUN pip3 install --no-cache-dir -r requirements.txt
CMD PYTHONPATH=`pwd` python tests-integration/integration_app.py